// GENERATED by scripts/sync-knowledge.mjs — do not edit by hand.
// Re-run `npm run sync-knowledge` after changing either source document.

export const ONE_PIECE_KNOWLEDGE = `نظريات القطعة الواحدة

**سعد**

\\-----------------------------------------------

حلم لوفي شي سخيف

السلاح مال ايمو ساما اورانوس

سابو ماصاده شي

كوينا بترجع(عزيمة و يا قرام)

باغي بصير ملك القراصنة قبل لوفي (تحدي ويا حسين PC)

اكاينو سوى فرقة السورد

~اوكيجي من فرقة السوورد~

كيزارو بخون البحريه

مكافأة دراغون أعلى من روجر(كرك الجتري)

دراغون عنده فاكهة لوغيا الرياح

لوفي بكون عنده تحكم كامل في الاسلحه الاسطوريه

~جوليري بوني استنساخ البيق المام (عزيمة كرك قرام) (عزيمة كرك حسين)~

ويفل استنساخ وايتبيرد

تاشيقي استنساخ كوينا(عزيمة كرك حسين)

ايموساما ام لوفي

كروكودايل كان بنيه

السيرافيم يكبرون مع الوقت(عزيمة كرك قرام)

البيق مام ما ماتت

شانكس لقوه في القود فالي وهو صغير و خذه روجر

ايمو ساما خالدة من سبت فاكهة لاو ope ope no mi

الرجل ذو الجرح الناري هو سكوبر قابان او اوشوكو(وانغ زي)

تيتش خطف كوبي عشان يشارك في الريفري و يتقرب من التنانين السماوية خصوصا ايمو ساما لانه يبي شي منها

شيراهوشي من الدي

فرانكي بياخذ فاكهة كوما عقب ما يموت(عزيمة عشى حسين)

اورانوس هي مركبة فضائية تستطيع الوصول إلى القمر

اورانوس هي المركبة المستخدمه لتدمير المملكة القديمة

الجوي بوي القبلي اسمه ديراس او داراس

نيوغيت من عرق البوكانيير

جوي بوي السابق من نسل العمالقة

مكافئة لوفي الاخيرة بتكون 6.8 مليار او 5.6 مليار

لوفي بصيده نفس مرض روجر

لوفي بموت اول واحد في الطاقم

اينيل بيرجع بسفينته او شي يشبه سفينته ارك ماكسميم

باغي هو الي بيحصل البونقليف الاخير اول

بوني بتنظم للجيش الثور

سانجي عنده هاكي ملكي

~الملك هارالد ابو كايدو~

لوكي بصير ملك الباف

كيد بيطلع في الباف و بيساعد لوفي (كرك الجتري)

تيتش قدر ياكل فاكهتين لان الروكس داخله فصارو شخصين في جسد واحد

كوينا بتشق ميهوك و بتشوف زورو و زورو بشقها و بصير اقوى سياف

تيتش بدش الباف

**قرام**

شانكس من التينريوبي

تاشيقي هي كوينا(هبد الارض)

ايمو ساما اخت او اخو الجوي بوي (عزيمة كرك)

زوجة اودن بنت الجوي بوي (عزيمة كرك )

~شانكس من الفرسان المقدسين~

تيتش قدر ياكل فاكهتين بسبة عرق ابوه او امه

~فاكهة زيبيك هي نفسها مالت تيتش الظلام~

الي يتخاطرون من ال دي

ايمو كان يحسد جوي بوي على فاكهته

\\---------------------------------------------------------------------------------------------------

**حسين**

~الشخص الي من الفرسان المقدسة هو الي كب الخمر على شانكس (عزيمة عشى)(هبد)~

لوفي بصير ملك القراصنة قبل باغي

~شانكس من ال دي~

\\--------------------------------------

**بدور**

كنز الون بيس هو ورقة شفافة تشوف فيها روحك كأنها مراية

واحد من طاقم لوفي بموت في نهاية القصة

**Kasb**

~لوفي بيمتص قوة المذرفليم و بشق الغوروسي~

حاكم الشمس الشرير

ايمو ساما طيب

\\* بيطلع من الج

ايمو ساما ام شانكس

لوفي بينشق و بيعطي طاقمه قوة (قوة الصداقة) و بيشقون ايمو كلهم (هبد الارض)

اينيل بيرجع و بكون في صف لوفي

في شخصية مهمة موجودة بس محد لاحظها بتطلع بعدين

لوفي بموت من الضحك و بموت وهو يضحك

لوفي بلبس القبعة لشخص قبل مايموت

ايمو أبو ميهوك او في صله بينهم

كوبي بياكل فاكهة و ايمو بتتحكم بكوبي

اوسوب بموت اول واحد في الطاقم

**علولي**

**اوسوب عنده فاكهة شيطان بس خاشها او قوة بس خاشها(سعد , جتري كرك)**

**اوسوب بتهاوش مع واحد من الطاقم و بفوز عليه**

**اوسوب بصير واحد من اقوى الاشخاص في الطاقم توب 3 على الاقل**

**GTR**

**~شانكس شرير مو في صف لوفي و في رافتيل بقوله ذي الحجي~**

**لوكي بينضم لاسطول لوفي و بيخضع للعم(عزيمة كرك سعد)**

**شانكس بيتواجه مع تيتش و شانكس بيشقه(عزيمه كرك سعد)**

**دراغون بيتواجه مع اكانيو**

**ايمو ساما بتسيطر على جسد تيتش في المستقبل و بتسخدمه كاحد جنودها للحرب ( عزيمة روسي الجابرية سعد)**

**لوكي بصير قائد القوات حق الباف**

**الادميرال الي مات هو ابو اكاينو**

**ميهوك ولد ريلي (هبد الارض)**

**لاو بينظم للجيش الثور**

**لوكي من الدي**

**هيمنة السواد تضبط مع سكان الجزيرة فقط**

**ايمو يبي فيفي عشان يتزوجها**

**نامي بتاكل فاكهة**

**عمر**

**الي عنده البونقليف الأخير هو ديفي جونز**

**ايمو عندها علاقة حب مع ديفي جونز**

**ايقاظ فاكهة تشوبر هي حاكم الغابة(هبد الارض)**

**في منتصف القرن المفقود، كان هناك مشروع سري يُعرف باسم “مشروع ديفي”، تجربة علمية حاولت فيها مجموعة من العلماء الوصول إلى مفهوم الخلود ليس من خلال الزمن، بل عبر الذاكرة الجينية. ووفقاً للوثائق القليلة التي نجت من الحذف التاريخي، فإن هذا المشروع لم يكن مجرد بحث في علوم الاستنساخ، بل محاولة لإعادة تشكيل إرادة العالم عبر أجساد جديدة يمكنها حمل “الوعي الأصلي” للبشرية. يُعتقد أن هذا المشروع تم تمويله من قبل إحدى الفصائل القديمة التي كانت تنافس حكومة العالم في بداياتها، فأنشأوا مختبراً تحت البحر لتجنب اكتشافهم، مستخدمين تكنولوجيا لا يُعرف مصدرها حتى اليوم. بعض المؤرخين يشيرون إلى أن فيغابانك لم يكن أول من لمس حدود العلم في هذا العالم، بل استكمل إرثاً أقدم منه بقرون، أُغلق خوفاً من نتائجه على الوجود ذاته.  
المثير في هذه النظرية أن “ديفي جونز” لم يكن شخصية أسطورية بحرية كما تصوّر القصص، بل أول تجربة ناجحة في نقل الوعي من جسد إلى آخر. تمت التضحية بمئات المتطوعين قبل الوصول إلى نتيجة، لكن الكائن الناتج لم يكن إنساناً بالمعنى المفهوم. فقد جسده قدرته على الثبات الفيزيائي، وذاب في البحر ليصبح شيئاً بين الحياة والعدم، يحتفظ بذكريات جميع من ماتوا غرقاً. ومع مرور الزمن، نُسيت الحقيقة، وتحوّل الاسم إلى خرافة. لكن آثار المشروع لم تختفِ. بعض من عملوا في المختبر تفرّقوا، وواصلوا تجاربهم سراً، لينتهي الأمر بولادة فكرة جديدة: استخدام تلك المعرفة في خلق كائنات بشرية معدّلة وراثياً، يمكنها النجاة في أي بيئة، مقاومة للمرض، متكيّفة مع الضغط الزمني والبحري، تحمل في داخلها توازن العالم الذي فشل ديفي جونز في الحفاظ عليه.  
من هنا تبدأ العلاقة الغريبة بين مشروع ديفي ومشروع جيرما. فبينما اشتهرت جيرما 66 كقوة عسكرية ذات تكنولوجيا بيولوجية متقدمة، تشير الوثائق المسربة إلى أن جزءاً من أبحاثها الأولى تم بناؤه على نتائج مستخلصة من بقايا مختبر ديفي. جادج، والد سانجي، لم يكن يسعى فقط إلى خلق جنود لا يُهزمون، بل كان يبحث عن طريقة لإعادة بعث الإنسان المثالي، الإنسان الذي يمكنه تجاوز حدود الإرادة البشرية. ولهذا السبب كانت تجاربه محظورة في البداية. لكنه لم يكن يعلم أن أحد العلماء العاملين معه — شخصية مجهولة الاسم يُعتقد أنها فيغابانك قبل انشقاقه — قد سرق النسخ الجينية التسع التي تمثل جوهر مشروع ديفي وأخفاها في البحر الشرقي. هناك، في قرية صغيرة، بدأت مرحلة جديدة من التاريخ.  
النسخ التسع تم تخزينها في خلايا حيوية، داخل أجسام أطفال تم اختيارهم بعناية. هؤلاء الأطفال، بمرور الزمن، أصبحوا ما نعرفه الآن باسم “طاقم قبعة القش”. لوفي، بحسب هذه الفرضية، ليس مجرد مستخدم لفاكهة شيطانية، بل هو نموذج حيوي صُمّم ليحمل الطاقة البدائية التي وُجدت في نيكّا — طاقة الذاكرة الإلهية التي لا يمكن تدميرها. خصائص جسده المطاطي لا تأتي من الفاكهة فحسب، بل من مادة جينية تسمح بإعادة تشكيل الخلايا بشكل لحظي، وهي التقنية ذاتها التي استخدمها العلماء لإعادة بناء ديفي جونز. قدرته على النجاة من كل ما يتعرض له ليست حظاً، بل خاصية بيولوجية موروثة من ذلك الكائن الأول. زورو، في المقابل، يحمل جينات الوحدة السادسة من المشروع، الوحدة المسؤولة عن “الازدواج القتالي”، وهي التي تفسّر انفصاله الدائم عن الواقع المادي، إذ يتحرك كأنه يعيش في بعدٍ آخر. هذه الخاصية تجعله يتبع هدفه الغريزي حتى عندما يفقد الاتجاهات، كأن جسده يذكر شيئاً عقله نسيه.  
نامي تمثل نموذجاً مختلفاً تماماً. النظرية تفترض أن جسدها يحتوي على خلايا تتفاعل مع التغيرات الكهرومغناطيسية في الغلاف الجوي، مما يمنحها حاسة سادسة تجاه الطقس والرياح. بعض العلماء يعتقدون أن هذا النمط الجيني كان جزءاً من مشروع فرعي اسمه “الاستشعار السماوي”، الغرض منه خلق كائنات قادرة على التنبؤ بالعواصف لحماية جزر العالم القديم. سانجي، من ناحية أخرى، هو الحالة الأكثر إثارة للجدل. هناك فرضية تقول إنه أول استنساخ بشري تمت محاولة “تلطيفه عاطفياً” عبر تعطيل المسار الكيميائي المسؤول عن العدوانية. هذه العملية جعلته غير قادر على إيذاء النساء، لكنها أيضاً جعلته ناقصاً في عين جادج، الذي تخلّى عنه ظناً أنه فشل. لكنه في الحقيقة كان أقرب إلى النموذج المثالي للإنسان الكامل، الكائن الذي لا يقاتل من أجل البقاء، بل من أجل الآخرين.  
أما أوسوب، فهو الحلقة الغامضة في السلسلة. تشير النظرية إلى أنه النموذج رقم صفر، النسخة الأولية التي جُرّبت فيها خاصية جديدة اسمها “التجسيد الإدراكي”، وهي القدرة على جعل التصورات الذهنية واقعاً محتملاً. بعبارة أبسط، عندما يكذب أوسوب، تتفاعل ذبذبات دماغه مع المجال الإدراكي للعالم، مما يخلق احتمالات تجعل أكاذيبه أقرب للحقيقة. وهذا يفسر سبب تحقق بعض كذباته فعلاً. روبين، من جانبها، تمثل النموذج السابع في المشروع، حيث تم دمج جيناتها مع خلايا نباتية قادرة على التضاعف. قدرتها على استنساخ أطرافها ليست فاكهة شيطانية، بل نتاج تصميم بيولوجي يُمكّن الخلايا من إعادة بناء نفسها بشكل مستقل، وهي خاصية مأخوذة من أبحاث أُوهارا حول تطور المعرفة الحية. لهذا السبب فقط يمكنها قراءة النصوص القديمة، لأنها مبرمجة وراثياً لاستيعاب الذاكرة الجماعية للتاريخ.  
فرانكي هو التجربة الميكانيكية في المشروع. نصفه البشري مرتبط بخلايا مبرمجة للتفاعل مع المعدن عبر إشارات كهروحيوية، مما يجعل جسده مزيجاً بين التقنية والبيولوجيا. هذا يفسر قدرته على الاندماج مع السفن والآلات بشكل يتجاوز حدود الفهم البشري. شوبر، في المقابل، كان تجربة لدمج الوعي الحيواني بالذكاء البشري لإثبات أن “العقل” ليس حكراً على الإنسان. دماغه يعمل على تردد مزدوج، نصفه منطقي والنصف الآخر غريزي، ما يجعله قادراً على التنقل بين التفكير العلمي والعاطفة الفطرية بانسجام نادر. أما بروك، فهو تجسيد لفكرة الذاكرة الخالدة. عندما مات، بقي وعيه في الطيف الصوتي الذي تركه مشروع ديفي، ثم عاد جسده للحياة حين وجد تردداً متطابقاً مع تلك الذاكرة، ما جعله يعيش كمجموعة من النوتات الحية.  
القبعة التي يحملها لوفي تمثل العنصر الأهم في النظرية. فبحسب التحليل، القبعة ليست مجرد رمز أو إرث من روجر، بل قطعة من التقنية القديمة. في نسيجها الخارجي توجد ألياف دقيقة من الذهب الحيوي، مادة كانت تُستخدم لتخزين البيانات الجينية في العصور القديمة. هذه الألياف تعمل كجهاز تذكّر، يحمل داخله بقايا المشروع الأول. لذلك، كل من يرتدي القبعة يُصبح جزءاً من “شبكة الإرادة”، وهي الحقل الحيوي الذي يربط بين حاملي الـ D. لهذا شعر روجر بأنه أكمل رحلته حين سلّم القبعة، لأن ذاكرة المشروع انتقلت إلى الجيل التالي. في هذا السياق، الون بيس نفسه ليس كنزاً مادياً، بل الذاكرة الأصلية للعالم — شيفرة الوعي التي تحتوي على تاريخ البشرية قبل أن تمحوه الحكومة العالمية.  
مع كل هذه التفاصيل، تنهار النظرية تحت أول اختبار علمي جاد. لا توجد أي وسيلة لإثبات وجود “الانعكاس الزمني للخلايا”، ولا دليل على أن الوعي يمكن نقله وراثياً. كل ما في الأمر أن الأحداث تتقاطع بشكل يثير الوهم بالترابط. لكن الغريب أن الكثير من الحقائق في القصة — من مرونة لوفي الخارقة، إلى حسّ نامي الجوي، إلى وعي روبين التاريخي — تتوافق بشكل غريب مع ملامح المشروع الموصوف. ربما لا تكون النظرية حقيقية من الناحية العلمية، لكنها تطرح سؤالاً فلسفياً عميقاً: هل الإنسان نتاج مصادفة، أم نتيجة مشروع قديم لم يكتمل بعد؟ هل الحرية التي يسعى إليها لوفي مجرد غريزة، أم استدعاء لا واعٍ لذاكرة خُتمت قبل ثمانمئة عام؟  
إذا نظرنا إلى رحلتهم ككل، نجد أن كل فرد من الطاقم يسعى لاكتشاف ذاته، وكأنهم في الحقيقة يبحثون عن الأصل، عن التجربة التي وُلدوا منها. جزيرة الون بيس ليست موقعاً جغرافياً بقدر ما هي النقطة التي يلتقي فيها الماضي بالوعي، حيث يدرك كل منهم الحقيقة: أنهم ليسوا مجرد بشر، بل مرآة للإنسانية القديمة التي حاولت النجاة من نسيانها. في النهاية، تنهار النظرية علمياً، لكنها تظل متماسكة من الناحية الرمزية. إنها تذكير بأن الأسطورة قد تكون الطريقة الوحيدة التي يترك بها العلم بصمته في التاريخ، وأن إرادة الـ D ليست سلالة من الدم، بل سلالة من الذاكرة. وربما، في مكان ما من هذا العالم، هناك من لا يزال ينتظر اكتمال المشروع.**`;

export const DAILY_CHALLENGES_GUIDE = `# Daily Challenges — site guide (for the assistant)

This is the reference the website assistant uses to answer questions about the
**Daily Challenges** site. Everything a player can ask about the site, its games,
coins, streaks, the shop and the weekly boss should be answered from here. If a
detail isn't here, say so plainly — don't invent rules.

## What the site is

A daily-challenge hub tied to the Discord server. You sign in with Discord. Every
day there is a fresh set of small games. Coins are the server currency, handled by
the UnbelievaBoat bot (the same balance shown in Discord). Your coin balance has
**cash** (on hand) and **bank** (banked); the header shows both plus the total.

**One grace per day:** each game can be *completed* once per day for its reward.
After that the game still opens but pays nothing until the next daily reset.

**Daily reset** happens at **midnight in the challenge timezone (Asia/Bahrain)**.
"Today" everywhere on the site means that day.

## The games

There are six sections. Each has its own page and its own reward.

| Game | Path | What you do |
|---|---|---|
| Wordle | \`/wordle\` | Guess the day's 5-letter word. |
| Typing Test | \`/typing\` | Type the passage accurately and fast. |
| Aim Trainer | \`/aim\` | Hit the targets before the timer runs out. |
| The Litany | \`/litany\` | Memorise and repeat a growing sequence. |
| Geometry Dash | \`/geodash\` | A staked auto-runner — see its own section below. |
| Boss Raid | \`/boss\` | The weekly co-op fight — only live on its window (see below). |

Default rewards (the server owner can change these): Wordle 250, Typing 200,
Aim 200, Litany 200. Geometry Dash has no fixed reward — it is a staked game.

### Retry rules (per game, per day)

- **Wordle** — the standard six guesses. Get it in six to complete the day.
- **Typing** — the first several failed attempts are free. Past that, each further
  fail lowers that day's typing prize; once the prize would reach zero, the day's
  typing is **failed** (locked until reset).
- **Aim** — a few losing runs are allowed; after that the day's aim round is
  **failed**.
- **The Litany** — you pass the day by clearing a sequence of a set length. Going
  further than that on a successful run adds a small bonus to the prize, up to a
  ceiling.

Exact numbers are set by the server owner and can change; if asked for the precise
current value, say it depends on the server's configuration.

### Geometry Dash (\`/geodash\`) — the staked game

A pay-to-play auto-runner. **One paid run per day.** You choose a difficulty, the
fee is charged up front, and the run starts blind (no preview, no practice).

- **Difficulties:** Easy, Medium, Hard, Impossible. The difficulty you pick is
  **locked for the rest of that day** — you can't switch.
- **Easy / Medium / Hard:** a fixed entry fee (default 100 coins). Winning pays the
  fee back plus a reward — a net gain of roughly +100 (easy), +300 (medium),
  +500 (hard). The confirm screen shows the exact fee and reward.
- **Impossible:** you choose your own stake (a minimum applies, default 5000, no
  maximum). A win pays **5× your stake**.
- **Dying forfeits the stake.** No payout.
- **Free restarts:** after a death you can restart a limited number of times per
  fee (default 5) at no extra cost. Run out of restarts and you must pay the fee
  again to keep going — on Impossible, re-paying lets you pick a new stake and the
  5× payout is on that new stake.
- Restarts reset when you re-pay and at the daily reset.
- **Abandoning** a run you never finished (and never died on) refunds the stake and
  does **not** use up the day's run. A network or loading failure refunds too.
- A win counts as a completion (it credits your streak / perfect day). A loss shows
  the red "Failed" stamp for the day.
- The obstacle set includes spikes, blocks, ceiling hazards, floating bars, moving
  crushers/sweepers, spinning blades, jump orbs and jump pads. Orbs briefly slow
  time and zoom in to help you land the tap.

### Weekly Boss — "Veyrath, The Hollow Sovereign" (\`/boss\`)

A once-a-week co-op raid. It spawns **Saturday at 16:00 (Asia/Bahrain)** and
vanishes at **23:59** the same day. The Discord server gets an announcement when it
spawns.

- You fight by **clicking** — every click chips its health down.
- **If the raid kills it:** a reward pool is split between everyone who fought, in
  proportion to the damage they dealt. Payouts land when the window closes.
- **If it survives:** every fighter loses a fixed penalty in coins.
- Boss name, health, reward pool, penalty and schedule are set by the server owner
  on the admin side and can change week to week.

## Streaks, perfect days, ranks

- Completing *any* game on a day keeps your **streak** alive; missing a whole day
  breaks it.
- A **perfect day** is completing every game that day.
- \`/leaderboard\` ranks players by streak.
- \`/me\` shows your own record — streak, best scores per game, history.

## The shop (\`/shop\`)

Buy things with **banked** coins. Payment comes off immediately and the reward
(currently Discord roles) is applied by the bot right away. Temporary passes are
removed automatically when they expire.

**Right now the shop is empty** — it shows a "wares coming soon" state. New items
and ranks will appear there later. Tell players to bank their coins so they're
ready.

## Support / bugs / suggestions

There is no support form on the website. To report a bug or suggest something,
players use the Discord bot's **\`/report\`** slash command — it opens a short form
and sends it straight to the server owner.

## If the assistant itself is failing

If the assistant can't reach its language model, the site shows a message saying
the assistant is temporarily unavailable and that the keeper (owner) has been
alerted automatically. Players should just try again a little later.`;
